#!/usr/bin/bash
source_directory="."
destination_directory="/tmp/u"

for file in "$source_directory"/*; do
    filename=$(basename "$file")
    first_character=${filename:0:1}

if [[ "$first_character" == [[:upper:]] ]]; then
        mv "$file" "$destination_directory"
        echo "Moved $filename to $destination_directory"
    fi
done

